---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - "^monumentos_de_america\\s*$"
  - "^postres_favoritos\\s*$"
name: Listas de diccionarios
