---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - "^marte\\s*$"
  - "^mercurio\\s*$"
  - "^saturno\\s*$"
  - "^listo\\s*\\(\\s*\\)\\s*$"
name: Los campos de Marte
